language: python
python:
    - "2.7"
# command to install dependencies
install:
    - pip install -r requirements.txt
    - python gen_login_details_file REDDITUSER REDDITPASSWORD
# command to run tests
script:
    - cd tests
    - py.test

branches:
    only:
        - master
